name: playback_emby
description: Emby playback plugin.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  playback_core:
    path: ../playback_core
  server_core:
    path: ../server_core
  logger: ^2.5.0
